[tool.ruff.lint]
select = ["F", "E", "W", "I"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
setuptools = "^75.6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

